version: '3'

services:
  web:
    build: .
    ports:
      - "5000:80"
    depends_on:
      - redis
    environment:
      ConnectionStrings__Redis: "172.17.0.5:6379"
      ApplicationSettings__RedisInstanceName: "starship_key"

  redis:
    image: redis
